name: MavBox
author: Dustin Hansen
category: Interface
tags: [dialog, utility, UI, window]
docs: http://maveno.us/library/examples/html5/mavbox
demo: http://maveno.us/library/examples/html5/mavbox
current: 0.2
